name: Pipeline Laboratorio Final DevSecOps
on:
  push:
    branches:
      - feature-labfinal

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Set Environment Variables
        run: |
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "ORG_NAME=rmedina-cursodevsecopsusach" >> $GITHUB_ENV


      - name: Variable
        run: echo "$BRANCH_NAME"


      - name: Validando existencia de proyecto en SonarCloud
        id: validateProjectOnSonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo ${{ github.event.repository.name }}
          echo "Verificando si el proyecto $REPO_NAME existe en SonarCloud..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -u "$SONAR_TOKEN:" \
           "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")
          echo "$response"  

          if [ "$response" -ne 200 ]; then
            echo "El proyecto no existe. Creándolo en SonarCloud..."
            create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/projects/create" \
              -d "name=$REPO_NAME" \
              -d "project=$REPO_NAME" \
              -d "organization=$ORG_NAME" \
              -d "visibility=public")
            if [ "$create_response" -ne 201 ]; then
              echo "Proyecto creado exitosamente (HTTP Response: $create_response)."
            fi

            echo "Estableciendo la rama [$BRANCH_NAME] como predeterminada..."
            curl -s -f -X POST -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/project_branches/rename" \
              -d "name=$BRANCH_NAME" \
              -d "project=$REPO_NAME"

            echo "project_created=true" >> $GITHUB_ENV
          else
            echo "El proyecto ya existe en SonarCloud."
            echo "project_created=false" >> $GITHUB_ENV
          fi

      - name: Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          echo "Validando estado del Quality Gate"
          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')

          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')

          if [ "$qualityGateStatus" != "OK" ]; then
            echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus."
            echo "Verificando vulnerabilidades críticas..."
            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')

            if [ "$vulnerabilities" -gt 0 ]; then
              echo "Se encontraron $vulnerabilities vulnerabilidades críticas. El proyecto no cumple con los estándares de seguridad."
              exit 1
            else
              echo "No se encontraron vulnerabilidades críticas ($vulnerabilities vulnerabilidades) . El proyecto cumple con el Quality Gate." 
            fi
          fi

  SCA:
      needs: SAST
      runs-on: ubuntu-24.04

      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Install Dependencies
          run: npm install

        - name: Dependency Check
          uses: dependency-check/Dependency-Check_Action@1.1.0
          id: depcheck
          with:
            project: '${{ github.event.repository.name }}'
            path: '.'
            format: 'HTML'
            args: >
              --out ./reports
              --failOnCVSS 5
              --enableRetired

        - name: Upload Dependency Check Report
          uses: actions/upload-artifact@v3
          with:
            name: Dependency Check Report
            path: ./reports