name: Workflow
on:
  push:
    branches:
      - feature-labfinal
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 

      - name: Set up JDK 17
        uses: action/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'