name: Workflow
on:
  push:
    branches:
      - feature-labfinal
jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Chekout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'
      
      - name: Sec Enviroment Variables
        run: echo "BRANCH_NAME= ${{ github.ref_name }}" >> $GITHUB_ENV